spring:
  datasource:
    url: jdbc:mysql//localhost:3306/essentials_filiere?createDatabaseIfNotExist
    username: root
    password: Mombijou1
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStandardStrategyImpl
      ddl-auto: none 
      

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MYSQL5Dialect