spring:
  datasource:
    url: jdbc:mysql://localhost:3306/essentials_nioundb?createDatabasaIfNotExist=true
    username: root  
    password: ******1 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate: 
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      
       