spring:
  datadource:
    url: jdbc::mysql:://localhost:3306/essentials_payment?cretaDatabaseIfNotExist=true
    username: root
    password: Mombijou1
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
spring.jpa.propertis.hibernate.dialect: org.hibernate.dialect.MySQl5Dialect